#!/bin/bash
if [ $# -lt 2 ]
then
	echo "Will generate raw chromosomal maps for two tagDirs, create images and differential images of the maps using HiCMapCombiner"
	echo ""
	echo "Usage: getDiffMaps <HiCDir1> <HiCDir2> " 
else
	for chr in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y
	do
		analyzeHiC $1 -pos chr${chr} -raw -res 100000 > $1/chr${chr}_raw100k.txt
		analyzeHiC $2 -pos chr${chr} -raw -res 100000 > $2/chr${chr}_raw100k.txt
		HiCMapCombiner $1/chr${chr}_raw100k.txt $2/chr${chr}_raw100k.txt
		echo "Done with chr${chr}"
	done
fi
