#!/bin/bash
if [ $# -lt 2 ]
then
	echo "Greps out the lines in file 2 containing lines in file 1 and outputs to stdout"
	echo "Usage: grabLines which_lines.file from_file.file"
else
	
	for line in $(cat $1); do grep ${line}$'\t' $2; done
fi
