---
title: "PCAplot"
author: "IGC"
date: "8/21/2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("ggplot2")) {
  install.packages("ggplot2", repos="http://cran.cnr.berkeley.edu/", dependencies= TRUE)
  library(gplots)
}
if (!require("ggfortify")) {
  install.packages("ggfortify", repos="http://cran.cnr.berkeley.edu/", dependencies= TRUE)
  library(ggfortify)
}
```



```{r eruptions, echo=FALSE}
inputPanel(
  fileInput("fpkm_file","Choose your HOMER fpkm table",
            accept = c("text","text",".txt"))
)

renderPlot({
  inFile<- input$fpkm_file
  if( is.null(inFile))
    return(NULL)
  data <- as.matrix(read.delim(file = inFile$datapath,header = TRUE, sep = "\t"))
  data2 = data[,9:dim(data)[2]]
  data2b = data[,9:dim(data)[2]]
  for( i in 1:dim(data)[1]) 
  {
    data[i,8]= strsplit(data[i,8],"[|]")[[1]][1]
    if( i %% 1000==0)
      cat(".")
  }
  data2= matrix(as.numeric(data2)+5,nrow=dim(data2)[1],ncol=dim(data2)[2])
  data2b= matrix(as.numeric(data2b)+5,nrow=dim(data2b)[1],ncol=dim(data2b)[2])
  rownames(data2) <- data[,8]
  colnames(data2) <- colnames(data[,9:dim(data)[2]])
  data3= log(data2[apply(data2[,-1], 1, function(x) !all(x<32)),])
  colnames(data3)=strtrim(colnames(data3),rep(20,length(colnames(data3))))
  pr=prcomp(t(data3),scale = TRUE,center=TRUE)
  pr$x=pr$Y[,1]
  pr$y=pr$Y[,2]
  autoplot(pr,label.size = 1,cex=0.5,main = sprintf("PCA for %s",inFile$datapath),xlab = sprintf("PC1 %3.1f",pr$sdev[1]), ylab=sprintf("PC2 %3.1f",pr$sdev[2]),labels=colnames(nearPoints(pr,input$plot_click, xvar="x",yvar="y")))

})
```
