#!/bin/bash
if [ $# -lt 1 ]
then
	echo "Usage: runHiC genome_or_fasta"
else
	echo "Starting HiC analysis: makingTagDirs, filtering, analyzeHiC, HiCEntropy" 
	for i in *_R1*.sam
	do 
		NAME=${i%_S*Aligned.out.sam}
		R2=${i/_R1/_R2}
		makeTagDirectory $NAME $i,$R2 -tbp 1
		cp -r $NAME ${NAME}_filtered
		rm ${NAME}_filtered/*ERCC*
		makeTagDirectory ${NAME}_filtered -update -genome $1 -restrictionSite GATC -both -removeSelfLigation -removePEbg -removeSpikes 10000 5
		HiCChrImages ${NAME}_filtered 
	done
	echo "DONE!"
fi
