#!/bin/bash
if [ $# -lt 2 ]
then
	echo "Usage: venn list1 list2 > overlapSummary.txt"
else
	common=$(comm -3 $1 $2| wc -l)
	one=$(comm -1 $1 $2 | wc -l)
	two=$(comm -2 $1 $2 | wc -l)
	echo -e "$1\t$one" 
	echo -e "$2\t$two" 
	echo -e "$Common\t$common" 
fi
